[workers]
worker ansible_host=172.17.112.1 ansible_port=2222 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/deployment_lab4 ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[db]
db ansible_host=172.17.112.1 ansible_port=2223 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/deployment_lab4 ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
db_host=172.17.112.1
db_port=5432
app_port=8000
app_interface=127.0.0.1